apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cognitora.fullname" . }}
  labels: {{- include "cognitora.labels" . | nindent 4 }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets: {{- toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
