# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cognitora.v1 import common_pb2 as cognitora_dot_v1_dot_common__pb2
from cognitora.v1 import kv_pb2 as cognitora_dot_v1_dot_kv__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cognitora/v1/kv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KvStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lookup = channel.unary_unary(
                '/cognitora.v1.Kv/Lookup',
                request_serializer=cognitora_dot_v1_dot_kv__pb2.Hash.SerializeToString,
                response_deserializer=cognitora_dot_v1_dot_common__pb2.BlockInfo.FromString,
                _registered_method=True)
        self.BatchLookup = channel.unary_unary(
                '/cognitora.v1.Kv/BatchLookup',
                request_serializer=cognitora_dot_v1_dot_kv__pb2.HashList.SerializeToString,
                response_deserializer=cognitora_dot_v1_dot_kv__pb2.BlockInfoList.FromString,
                _registered_method=True)
        self.Promote = channel.unary_unary(
                '/cognitora.v1.Kv/Promote',
                request_serializer=cognitora_dot_v1_dot_kv__pb2.Hash.SerializeToString,
                response_deserializer=cognitora_dot_v1_dot_common__pb2.Status.FromString,
                _registered_method=True)
        self.PutBlock = channel.unary_unary(
                '/cognitora.v1.Kv/PutBlock',
                request_serializer=cognitora_dot_v1_dot_kv__pb2.PutBlockSpec.SerializeToString,
                response_deserializer=cognitora_dot_v1_dot_common__pb2.Status.FromString,
                _registered_method=True)
        self.Push = channel.unary_unary(
                '/cognitora.v1.Kv/Push',
                request_serializer=cognitora_dot_v1_dot_kv__pb2.PushSpec.SerializeToString,
                response_deserializer=cognitora_dot_v1_dot_common__pb2.Status.FromString,
                _registered_method=True)
        self.Pull = channel.unary_unary(
                '/cognitora.v1.Kv/Pull',
                request_serializer=cognitora_dot_v1_dot_kv__pb2.PullSpec.SerializeToString,
                response_deserializer=cognitora_dot_v1_dot_common__pb2.Status.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/cognitora.v1.Kv/Stats',
                request_serializer=cognitora_dot_v1_dot_kv__pb2.StatsRequest.SerializeToString,
                response_deserializer=cognitora_dot_v1_dot_kv__pb2.StatsResponse.FromString,
                _registered_method=True)


class KvServicer:
    """Missing associated documentation comment in .proto file."""

    def Lookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchLookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Promote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Push(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pull(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=cognitora_dot_v1_dot_kv__pb2.Hash.FromString,
                    response_serializer=cognitora_dot_v1_dot_common__pb2.BlockInfo.SerializeToString,
            ),
            'BatchLookup': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchLookup,
                    request_deserializer=cognitora_dot_v1_dot_kv__pb2.HashList.FromString,
                    response_serializer=cognitora_dot_v1_dot_kv__pb2.BlockInfoList.SerializeToString,
            ),
            'Promote': grpc.unary_unary_rpc_method_handler(
                    servicer.Promote,
                    request_deserializer=cognitora_dot_v1_dot_kv__pb2.Hash.FromString,
                    response_serializer=cognitora_dot_v1_dot_common__pb2.Status.SerializeToString,
            ),
            'PutBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.PutBlock,
                    request_deserializer=cognitora_dot_v1_dot_kv__pb2.PutBlockSpec.FromString,
                    response_serializer=cognitora_dot_v1_dot_common__pb2.Status.SerializeToString,
            ),
            'Push': grpc.unary_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=cognitora_dot_v1_dot_kv__pb2.PushSpec.FromString,
                    response_serializer=cognitora_dot_v1_dot_common__pb2.Status.SerializeToString,
            ),
            'Pull': grpc.unary_unary_rpc_method_handler(
                    servicer.Pull,
                    request_deserializer=cognitora_dot_v1_dot_kv__pb2.PullSpec.FromString,
                    response_serializer=cognitora_dot_v1_dot_common__pb2.Status.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=cognitora_dot_v1_dot_kv__pb2.StatsRequest.FromString,
                    response_serializer=cognitora_dot_v1_dot_kv__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cognitora.v1.Kv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cognitora.v1.Kv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Kv:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognitora.v1.Kv/Lookup',
            cognitora_dot_v1_dot_kv__pb2.Hash.SerializeToString,
            cognitora_dot_v1_dot_common__pb2.BlockInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchLookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognitora.v1.Kv/BatchLookup',
            cognitora_dot_v1_dot_kv__pb2.HashList.SerializeToString,
            cognitora_dot_v1_dot_kv__pb2.BlockInfoList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Promote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognitora.v1.Kv/Promote',
            cognitora_dot_v1_dot_kv__pb2.Hash.SerializeToString,
            cognitora_dot_v1_dot_common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognitora.v1.Kv/PutBlock',
            cognitora_dot_v1_dot_kv__pb2.PutBlockSpec.SerializeToString,
            cognitora_dot_v1_dot_common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Push(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognitora.v1.Kv/Push',
            cognitora_dot_v1_dot_kv__pb2.PushSpec.SerializeToString,
            cognitora_dot_v1_dot_common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pull(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognitora.v1.Kv/Pull',
            cognitora_dot_v1_dot_kv__pb2.PullSpec.SerializeToString,
            cognitora_dot_v1_dot_common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognitora.v1.Kv/Stats',
            cognitora_dot_v1_dot_kv__pb2.StatsRequest.SerializeToString,
            cognitora_dot_v1_dot_kv__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
