//! Rendering for `cgn-ctl install --target single-node`.
//!
//! Two outputs:
//!
//! * `cognitora.toml` — combined router + agent config consumed by both
//!   containers (each binary reads only the sections it cares about).
//!   `[security].require_mtls = false` because this is a localhost
//!   install; cloud / multi-node setups use the terraform / k8s targets.
//! * `compose.yaml` — three services (`etcd`, `router`, `agent`) on a
//!   user-defined bridge network with static IPs so `agent.listen` is
//!   dialable from the router. Identical shape to
//!   `examples/docker-ollama/compose.yaml`, just driven by config flags.
//!
//! The renderer is pure — all inputs flow in via [`Plan`], all outputs
//! flow out as `String`s — so the unit tests below don't need a docker
//! daemon.

use super::{Args, Engine};

/// Distilled inputs for the renderer.
pub struct Plan {
    pub model: Option<String>,
    pub hf_repo: String,
    pub engine: Engine,
    pub tp: u32,
    pub image: String,
}

impl Plan {
    pub fn from_args(args: &Args) -> Self {
        let model = args.model.clone();
        let hf_repo = match (&args.hf_repo, &model) {
            (Some(r), _) => r.clone(),
            (None, Some(m)) => m.clone(),
            (None, None) => String::new(),
        };
        Self {
            model,
            hf_repo,
            engine: args.engine,
            tp: args.tp.max(1),
            image: args.image.clone(),
        }
    }
}

pub fn render_toml(plan: &Plan) -> String {
    let mut s = String::with_capacity(2048);
    s.push_str("# Generated by `cgn-ctl install --target single-node`.\n");
    s.push_str("# Re-run the command (it's idempotent) to regenerate.\n\n");

    s.push_str("[agent]\n");
    s.push_str("node_id = \"node-0\"\n");
    s.push_str("listen  = \"0.0.0.0:7070\"\n");
    s.push_str("role    = \"both\"\n\n");

    s.push_str("[router]\n");
    s.push_str("listen_http  = \"0.0.0.0:8080\"\n");
    s.push_str("listen_admin = \"0.0.0.0:9091\"\n\n");

    s.push_str("[cluster]\n");
    s.push_str("etcd_endpoints = [\"http://etcd:2379\"]\n\n");

    s.push_str("[security]\n");
    s.push_str("require_mtls = false\n");
    s.push_str("# For multi-node deployments, run `cgn-ctl pki bootstrap`\n");
    s.push_str("# and set ca_file/cert_file/key_file to the generated paths.\n\n");

    s.push_str("[engine]\n");
    s.push_str(&format!("kind = \"{}\"\n", plan.engine.as_toml()));
    match plan.engine {
        Engine::Vllm => s.push_str("url  = \"http://127.0.0.1:8000\"\n"),
        Engine::Sglang => s.push_str("url  = \"http://127.0.0.1:30000\"\n"),
        Engine::LlamaCpp => s.push_str("url  = \"http://127.0.0.1:8080\"\n"),
        Engine::OpenaiCompat => {
            s.push_str("url  = \"http://host.docker.internal:11434\"\n");
            s.push_str("# ^ default points at a host-side Ollama; change to wherever your\n");
            s.push_str("# OpenAI-compatible engine actually listens.\n");
        }
    }
    s.push_str("kv_offload = \"none\"\n\n");

    s.push_str("[metrics]\n");
    s.push_str("listen          = \"0.0.0.0:9092\"\n");
    s.push_str("scrape_interval = \"10s\"\n");
    s.push_str("scrape_targets  = [\n");
    s.push_str("  { name = \"router\", url = \"http://router:9091/metrics\" },\n");
    s.push_str("  { name = \"agent\",  url = \"http://agent:9091/metrics\" },\n");
    s.push_str("]\n\n");

    if let Some(model) = &plan.model {
        s.push_str(&format!("[models.\"{}\"]\n", escape_toml_key(model)));
        match plan.engine {
            Engine::Vllm | Engine::Sglang => {
                s.push_str(&format!(
                    "hf_repo = \"{}\"\n",
                    escape_toml_string(&plan.hf_repo)
                ));
            }
            Engine::LlamaCpp => {
                s.push_str(&format!(
                    "path    = \"{}\"\n",
                    escape_toml_string(&plan.hf_repo)
                ));
            }
            Engine::OpenaiCompat => {
                // The model is whatever the upstream engine serves; we
                // just need a row so the router knows about it.
            }
        }
        s.push_str(&format!("tp      = {}\n", plan.tp));
    }
    s
}

pub fn render_compose(plan: &Plan) -> String {
    let mut s = String::with_capacity(4096);
    s.push_str("# Generated by `cgn-ctl install --target single-node`.\n");
    s.push_str("# Three containers on a user-defined bridge network: etcd for\n");
    s.push_str("# coordination, router, and agent. The OpenAI HTTP surface is\n");
    s.push_str("# published on host port 8080.\n\n");
    s.push_str("name: cognitora-single-node\n\n");
    s.push_str("services:\n");

    s.push_str("  etcd:\n");
    s.push_str("    image: quay.io/coreos/etcd:v3.5.15\n");
    s.push_str("    container_name: cognitora-etcd\n");
    s.push_str("    command:\n");
    s.push_str("      - /usr/local/bin/etcd\n");
    s.push_str("      - --name=cognitora-etcd\n");
    s.push_str("      - --listen-client-urls=http://0.0.0.0:2379\n");
    s.push_str("      - --advertise-client-urls=http://etcd:2379\n");
    s.push_str("      - --listen-peer-urls=http://0.0.0.0:2380\n");
    s.push_str("      - --initial-advertise-peer-urls=http://etcd:2380\n");
    s.push_str("      - --initial-cluster=cognitora-etcd=http://etcd:2380\n");
    s.push_str("      - --initial-cluster-state=new\n");
    s.push_str("    networks: [cognitora]\n");
    s.push_str("    ports:\n");
    s.push_str("      - \"2379:2379\"\n");
    s.push_str("    healthcheck:\n");
    s.push_str("      test: [\"CMD\", \"/usr/local/bin/etcdctl\", \"endpoint\", \"health\"]\n");
    s.push_str("      interval: 2s\n");
    s.push_str("      timeout: 2s\n");
    s.push_str("      retries: 15\n\n");

    s.push_str("  router:\n");
    s.push_str(&format!("    image: {}\n", plan.image));
    s.push_str("    container_name: cognitora-router\n");
    s.push_str("    depends_on:\n");
    s.push_str("      etcd: { condition: service_healthy }\n");
    s.push_str("    command:\n");
    s.push_str("      - /usr/local/bin/cgn-router\n");
    s.push_str("      - --config\n");
    s.push_str("      - /etc/cognitora/cognitora.toml\n");
    s.push_str("    volumes:\n");
    s.push_str("      - ./cognitora.toml:/etc/cognitora/cognitora.toml:ro\n");
    s.push_str("    networks: [cognitora]\n");
    s.push_str("    ports:\n");
    s.push_str("      - \"8080:8080\"  # OpenAI HTTP surface\n");
    s.push_str("      - \"9091:9091\"  # /metrics, /healthz, /readyz\n\n");

    s.push_str("  agent:\n");
    s.push_str(&format!("    image: {}\n", plan.image));
    s.push_str("    container_name: cognitora-agent\n");
    s.push_str("    depends_on:\n");
    s.push_str("      etcd: { condition: service_healthy }\n");
    s.push_str("    command:\n");
    s.push_str("      - /usr/local/bin/cgn-agent\n");
    s.push_str("      - --config\n");
    s.push_str("      - /etc/cognitora/cognitora.toml\n");
    s.push_str("    volumes:\n");
    s.push_str("      - ./cognitora.toml:/etc/cognitora/cognitora.toml:ro\n");
    if matches!(plan.engine, Engine::OpenaiCompat) {
        s.push_str("    extra_hosts:\n");
        s.push_str("      # so the agent can reach an engine running on the docker host\n");
        s.push_str("      - \"host.docker.internal:host-gateway\"\n");
    }
    if matches!(plan.engine, Engine::Vllm | Engine::Sglang) {
        s.push_str("    deploy:\n");
        s.push_str("      resources:\n");
        s.push_str("        reservations:\n");
        s.push_str("          devices:\n");
        s.push_str("            - driver: nvidia\n");
        s.push_str("              count: all\n");
        s.push_str("              capabilities: [gpu]\n");
    }
    s.push_str("    networks: [cognitora]\n");
    s.push_str("    ports:\n");
    s.push_str("      - \"7070:7070\"\n\n");

    s.push_str("networks:\n");
    s.push_str("  cognitora:\n");
    s.push_str("    name: cognitora\n");
    s.push_str("    driver: bridge\n");
    s
}

fn escape_toml_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn escape_toml_key(s: &str) -> String {
    // TOML bare keys allow [A-Za-z0-9_-]; any other character forces
    // a quoted key, in which case we just escape backslash and quote.
    escape_toml_string(s)
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::ValueEnum;

    /// Locks down the CLI surface for `--engine`: the values must match
    /// the TOML `[engine].kind` field exactly (snake_case), otherwise
    /// users hit confusing "invalid value" errors when copy/pasting from
    /// our own example configs.
    #[test]
    fn engine_flag_values_match_toml_kind() {
        for engine in Engine::value_variants() {
            let cli = engine
                .to_possible_value()
                .expect("engine variant should parse to clap value")
                .get_name()
                .to_string();
            assert_eq!(
                cli,
                engine.as_toml(),
                "CLI flag value should equal TOML kind for {engine:?}",
            );
        }
    }

    fn args_with(model: Option<&str>, engine: Engine) -> Args {
        Args {
            target: super::super::Target::SingleNode,
            model: model.map(String::from),
            hf_repo: None,
            engine,
            tp: 1,
            image: "ghcr.io/x/y:test".into(),
            out_dir: None,
            apply: false,
            chart: None,
            namespace: "cognitora".into(),
        }
    }

    #[test]
    fn toml_includes_all_required_sections() {
        let plan = Plan::from_args(&args_with(Some("llama3-8b"), Engine::Vllm));
        let out = render_toml(&plan);
        for needle in [
            "[agent]",
            "[router]",
            "[cluster]",
            "[security]",
            "[engine]",
            "[metrics]",
            "[models.\"llama3-8b\"]",
            "kind = \"vllm\"",
        ] {
            assert!(out.contains(needle), "missing `{needle}` in:\n{out}");
        }
    }

    #[test]
    fn toml_omits_models_section_when_no_model_given() {
        let plan = Plan::from_args(&args_with(None, Engine::Vllm));
        let out = render_toml(&plan);
        assert!(
            !out.contains("[models."),
            "expected no [models.*] in:\n{out}"
        );
    }

    #[test]
    fn toml_uses_path_for_llama_cpp() {
        let mut a = args_with(Some("tiny-cpu"), Engine::LlamaCpp);
        a.hf_repo = Some("/models/tiny.gguf".into());
        let plan = Plan::from_args(&a);
        let out = render_toml(&plan);
        assert!(
            out.contains("path    = \"/models/tiny.gguf\""),
            "out:\n{out}"
        );
        assert!(!out.contains("hf_repo = "), "out:\n{out}");
    }

    #[test]
    fn compose_includes_all_three_services() {
        let plan = Plan::from_args(&args_with(Some("llama3-8b"), Engine::Vllm));
        let out = render_compose(&plan);
        for needle in [
            "  etcd:",
            "  router:",
            "  agent:",
            "name: cognitora-single-node",
        ] {
            assert!(out.contains(needle), "missing `{needle}`");
        }
    }

    #[test]
    fn compose_adds_gpu_only_for_vllm_or_sglang() {
        let p_vllm = Plan::from_args(&args_with(Some("m"), Engine::Vllm));
        let p_sglang = Plan::from_args(&args_with(Some("m"), Engine::Sglang));
        let p_llama = Plan::from_args(&args_with(Some("m"), Engine::LlamaCpp));
        let p_oc = Plan::from_args(&args_with(None, Engine::OpenaiCompat));
        assert!(render_compose(&p_vllm).contains("driver: nvidia"));
        assert!(render_compose(&p_sglang).contains("driver: nvidia"));
        assert!(!render_compose(&p_llama).contains("driver: nvidia"));
        assert!(!render_compose(&p_oc).contains("driver: nvidia"));
    }

    #[test]
    fn compose_adds_host_docker_internal_only_for_openai_compat() {
        let p_oc = Plan::from_args(&args_with(None, Engine::OpenaiCompat));
        let p_vllm = Plan::from_args(&args_with(Some("m"), Engine::Vllm));
        assert!(render_compose(&p_oc).contains("host.docker.internal:host-gateway"));
        assert!(!render_compose(&p_vllm).contains("host.docker.internal:host-gateway"));
    }

    #[test]
    fn compose_picks_up_image_override() {
        let mut a = args_with(Some("m"), Engine::Vllm);
        a.image = "ghcr.io/foo/bar:custom".into();
        let plan = Plan::from_args(&a);
        let out = render_compose(&plan);
        assert!(out.contains("image: ghcr.io/foo/bar:custom"), "out:\n{out}");
    }
}
